version: "3.9"
services:
  api:
    container_name: api
    build: .
    ports:
      - "3003:3003"
    volumes:
      - .:/code
    links:
      - redis
    environment:
      - NODE_ENV=production
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    container_name: redis
    image: 'redis:alpine'
    restart: always
      