version: "3.9"
services:
  api:
    container_name: api
    build: .
    ports:
      - "3003:3003"
    volumes:
      - .:/host
      - ./dockerLogs:/app/logs
    environment:
      - NODE_ENV=production
    restart: always